name       : hedgewars
version    : 0.9.24.1
release    : 11
source     :
    - https://www.hedgewars.org/download/releases/hedgewars-src-0.9.24.1.tar.bz2 : 81360a41aa911a667163c25bed9a823e32b17ff130b328399ddcba049b5d5bb8
license    : GPL-2.0-only
component  : games.strategy
summary    : HedgeWars is a Worms! clone in all the best ways
description: |
    Hedgewars is a turn based strategy, artillery, action and comedy game, featuring the antics of pink hedgehogs with attitude as they battle from the depths of hell to the depths of space. As commander, it's your job to assemble your crack team of hedgehog soldiers and bring the war to your enemy.
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(physfs)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - fpc
libsplit   : no
setup      : |
    %cmake -DNOSERVER=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test || :
