name       : hedgewars
version    : 1.0.0
release    : 23
homepage   : https://www.hedgewars.org/
source     :
    - https://www.hedgewars.org/download/releases/hedgewars-src-1.0.0.tar.bz2 : 211634e61f2e4beecc3c98c6f749601fcd08321fda1ba969b3b3832a004f155b
license    : GPL-2.0-only
component  : games.strategy
summary    : Funny turn-based artillery game, featuring fighting Hedgehogs!
description: |
    Hedgewars is a turn based strategy, artillery, action and comedy game, featuring the antics of pink hedgehogs with attitude as they battle from the depths of hell to the depths of space. As commander, it's your job to assemble your crack team of hedgehog soldiers and bring the war to your enemy.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(freeglut)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(physfs)
    - fpc
libsplit   : no
setup      : |
    %cmake . -DNOSERVER=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test || :
