name       : hedgewars
version    : 0.9.22
release    : 8
source     :
    - http://download.gna.org/hedgewars/hedgewars-src-0.9.22.tar.bz2 : b699c8971ff420c3edd6533527ae2e99040f1e79207c9140826945bcf0e62192
license    : GPL-2.0
component  : games.arcade
summary    : HedgeWars is a Worms! clone in all the best ways
description: |
    HedgeWars is a Worms! clone in all the best ways
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(QtCore)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_ttf)
    - fpc
    - freeglut-devel
    - physfs-devel
libsplit   : no
setup      : |
    #sed -i "s/:=GL/:=gl/" hedgewars/options.inc
    %patch -p1 < $pkgfiles/hedgewars-ffmpeg3.patch
    %cmake -DCMAKE_RELEASE_TYPE=Release -DNOSERVER=1 \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/hedgewars.desktop $installdir/usr/share/applications/hedgewars.desktop
